service: s3-notifications

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "*"
  
  environment:
    EMAIL_ADDRESS: ${ssm:serverlessS3TutorialEmailAddress~true}
    EMAIL_PASSWORD: ${ssm:serverlessS3TutorialEmailPassword~true}

package:
  include:
    - mailer/**

functions:
  s3_notifications:
    handler: handler.s3_notifications
    events:
      - s3:
          bucket: ${env:BUCKET}
          event: "s3:ObjectCreated:*"
          # rules:
          #   - suffix: .pdf